# Generated by Django 4.1.4 on 2023-12-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instantconnect', '0003_remove_devices_id_devices_control_hub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
