# Generated by Django 4.1.4 on 2023-12-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantconnect', '0004_rename_devices_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='control_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instantconnect.controlhub'),
        ),
    ]
