# Generated by Django 4.1.4 on 2023-12-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instantconnect', '0005_device_id_alter_device_control_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='control_hub',
        ),
    ]
