# Generated by Django 4.1.4 on 2023-12-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantconnect', '0006_remove_device_control_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='control_hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instantconnect.controlhub'),
            preserve_default=False,
        ),
    ]
