# Generated by Django 4.1.4 on 2023-12-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instantconnect', '0010_alter_controlhub_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhub',
            name='bot_token',
            field=models.CharField(max_length=300),
        ),
    ]
